name: "blog"
mode: "dev"
port: 8082
version: "v1.0"
start_time: "2022-03-19"
machine_id: 2

log:
    level: "debug"
    filename: "blog.log"
    max_size: 200
    max_age: 30
    max_backup: 7

auth:
    jwt_expire: 8760

postgresql:
    host: 192.168.147.138
    port: 5432
    user: "postgres"
    password: "123456"
    dbname: "blog"
    sslmode: "disable"

redis:
    host: 127.0.0.1
    port: 6379
    password: ""
    db: 0
    pool_size: 100