name: "blog"
mode: "dev"
port: 8082
version: "v1.0"
start_time: "2022-03-19"
machine_id: 2

log:
    level: "debug"
    filename: "blog.log"
    max_size: 200
    max_age: 30
    max_backup: 7

auth:
    jwt_expire: 8760

mysql:
    host: 127.0.0.1
    port: 3306
    user: "root"
    password: "123456"
    dbname: "blog"
    max_open_conns: 200
    max_idle_conns: 50

redis:
    host: 127.0.0.1
    port: 6379
    password: ""
    db: 0
    pool_size: 100